"""create receipts table

Revision ID: 522bc34f99ed
Revises: 091f1c229ace
Create Date: 2026-07-25 12:51:34.423232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522bc34f99ed'
down_revision: Union[str, Sequence[str], None] = '091f1c229ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='uploaded', nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('merchant_detected', sa.String(length=120), nullable=True),
    sa.Column('total_amount_detected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_detected', sa.String(length=3), nullable=True),
    sa.Column('purchase_date_detected', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'processed', 'confirmed', 'failed')", name='ck_receipts_status_valid'),
    sa.CheckConstraint('total_amount_detected IS NULL OR total_amount_detected > 0', name='ck_receipts_total_amount_detected_positive'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_expense_id'), 'receipts', ['expense_id'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_expense_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
