"""add category visibility and system keys

Revision ID: 60fc06f3baba
Revises: 98a37f7627f0
Create Date: 2026-08-28 08:54:03.122600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fc06f3baba'
down_revision: Union[str, Sequence[str], None] = '98a37f7627f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('categories', sa.Column('system_key', sa.String(length=50), nullable=True))
    op.create_index('uq_categories_user_id_system_key', 'categories', ['user_id', 'system_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_user_id_system_key', table_name='categories')
    op.drop_column('categories', 'system_key')
    op.drop_column('categories', 'is_visible')
    # ### end Alembic commands ###
